name: Semantic release

on:
  push:
    branches:
      - feature/*
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Directory src
        working-directory: ./src
        run: ls -la
      - name: Install dependencies
        run: npm install
      # - name: Build app
      #   run: npm run build 
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release